projectVersion=0.2.0-SNAPSHOT
projectGroup=io.micronaut.fuzzing

title=Micronaut fuzzing
projectDesc=TODO
projectUrl=https://micronaut.io
githubSlug=micronaut-projects/micronaut-fuzzing
developers=Graeme Rocher
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.jvmargs=-Dfile.encoding=utf-8
